Install command fails with better errors. [semver:minor] (#32)

diff --git a/src/commands/install.yml b/src/commands/install.yml
--- a/src/commands/install.yml
+++ b/src/commands/install.yml
@@ -40,4 +40,16 @@ steps:
 
         HUGO_URL=https://github.com/gohugoio/hugo/releases/download/v<< parameters.version >>/hugo${HUGO_EXTENDED}_<< parameters.version >>_${OS}-64bit.${PKG_EXT}
 
-        curl -sSL "$HUGO_URL" | tar -xz -C /usr/local/bin hugo
+        # If the download fails...
+        if curl --fail -sSL "$HUGO_URL" 2>/dev/null | tar -xz -C /usr/local/bin hugo 2>/dev/null; then
+          echo "We're good, continue."
+        else
+          if [[ ! << parameters.version >> =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+            echo "Failed to install. The version number '<< parameters.version >>' is not a full valid SemVer version."
+          else
+            echo "Please choose a valid version from the Hugo tags page, without the leading 'v': https://github.com/gohugoio/hugo/tags"
+            echo "The download URL that failed was: ${HUGO_URL}"
+          fi
+
+          exit 1
+        fi
